# Configuration Jekyll
title: "AutoFlowAI"
description: "Expert freelance en automatisation IA avec n8n"
baseurl: "/site"
url: "https://ichem30.github.io"

# Configuration
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: "Accueil"
    url: "/"
  - title: "Services"
    url: "/services/"
  - title: "Portfolio"
    url: "/portfolio/"
  - title: "Contact"
    url: "/contact/"

# SEO
author: "AutoFlowAI"
social:
  name: "AutoFlowAI"
  links:
    - "https://linkedin.com/in/autoflowai"
    - "https://github.com/ichem30"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - deploy.ps1
  - astro.config.mjs
  - tsconfig.json
  - src/
  - dist/
